[package]
name = "pokemonoftheday"
version = "0.1.0"
authors = ["meowstic <meow@meowsticks.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.3", features = ["postgres"] }
